# Generated by Django 3.1.7 on 2021-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Product Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('small_image', models.ImageField(upload_to='products', verbose_name='Small Image')),
            ],
        ),
    ]
