#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset




if [ -z "${MYSQL_USER}" ]; then
    base_mysql_image_default_user='debug'
    export MYSQL_USER="${base_mysql_image_default_user}"
fi
export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"
echo ${DATABASE_URL}
mysql_ready () {
python << END
import sys
from os import getenv

import MySQLdb
try:
    db = MySQLdb.connect(host=getenv("MYSQL_HOST"),
                         user=getenv("MYSQL_USER"),
                         passwd=getenv("MYSQL_PASSWORD"),
                         db=getenv("MYSQL_DATABASE"),
                         port=int(getenv("MYSQL_PORT")))
    db.cursor()
except MySQLdb.OperationalError:
    print("EntryPoint: MySQL Operational Error")
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 1
done
>&2 echo 'MySQL is available'

exec "$@"
